language: elixir
matrix:
  include:
    - otp_release: 24.3
      elixir: 1.14.5
    - otp_release: 25.3
      elixir: 1.15.7
sudo: false
dist: focal
before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test
script:
  - mix test
cache:
  directories:
    - deps
    - _build
